id: P79B0D730
initial_creation_type: input
source_metadata:
  title: 'Mātṛceṭa: Śatapañcāśatka'
  language: en
  volumes:
    b863eb29237440a1b4eaba5567b63e68:
      title: 'Chapter 10: Mārgaāvatārastavaḥ'
      base_file: 'Chapter 10: Mārgaāvatārastavaḥ.txt'
      work_id: W997898C9
    043b52a60f154b7c8c695d95bb27296e:
      title: 'Chapter 11: Duṣkarastavaḥ'
      base_file: 'Chapter 11: Duṣkarastavaḥ.txt'
      work_id: WF85E969F
    a3e2eb4ebf394cd886a421598813c559:
      title: 'Chapter 12: Kauśalastavaḥ'
      base_file: 'Chapter 12: Kauśalastavaḥ.txt'
      work_id: W7E4471EF
    a23b7c44953f405f92ab1e591aaff6ae:
      title: 'Chapter 13: Ānṛṇyastavaḥ'
      base_file: 'Chapter 13: Ānṛṇyastavaḥ.txt'
      work_id: WD5A13933
    d799e67e5c7d4eb9859de0f4cbfed499:
      title: 'Chapter 1: Upodghātaḥ'
      base_file: 'Chapter 1: Upodghātaḥ.txt'
      work_id: W13F17542
    dd8305f06ed748658ea312df81ba4148:
      title: 'Chapter 2: Hetustavaḥ'
      base_file: 'Chapter 2: Hetustavaḥ.txt'
      work_id: W90CD47DD
    3cddea7ff9ce4f018c4fb784c67bb590:
      title: 'Chapter 3: Nirupamastavaḥ'
      base_file: 'Chapter 3: Nirupamastavaḥ.txt'
      work_id: W9A55B5D4
    76366f3bd9074177930b043eb2c94003:
      title: 'Chapter 4: Adbhutastavaḥ'
      base_file: 'Chapter 4: Adbhutastavaḥ.txt'
      work_id: WEB1A884B
    911790b0b8154cb18f7b8f33ceaf5794:
      title: 'Chapter 5: Rūpastavaḥ'
      base_file: 'Chapter 5: Rūpastavaḥ.txt'
      work_id: W6FF4BA62
    055f6783e8d54f2e9afe780cd1032fec:
      title: 'Chapter 6: Karuṇāstavaḥ'
      base_file: 'Chapter 6: Karuṇāstavaḥ.txt'
      work_id: W714A6885
    59e2e2eafb094ae89e6cee3639fc6dc5:
      title: 'Chapter 7: Vacanastavaḥ'
      base_file: 'Chapter 7: Vacanastavaḥ.txt'
      work_id: W0FEB09B0
    d9c9f4527b844d389509f947e5691898:
      title: 'Chapter 8: Śāsanastavaḥ'
      base_file: 'Chapter 8: Śāsanastavaḥ.txt'
      work_id: W5C9485E8
    cc173ef3e0264b0baf9a935536cc2cc3:
      title: 'Chapter 9: Praṇidhistavaḥ'
      base_file: 'Chapter 9: Praṇidhistavaḥ.txt'
      work_id: WAE34AE6A
    b78f250fd899403c9cfff0b4a0d56c53:
      title: Colophon
      base_file: Colophon.txt
      work_id: W40D8224D
    00f7b201a5734f65bcbf9d5f50a8595d:
      title: Preface
      base_file: Preface.txt
      work_id: WB965B04E
    020b48bedb7d446ab6b13ce4e06e119b:
      title: Title
      base_file: Title.txt
      work_id: W174146D0
  chapter_to_tile: {}
created_at: '2022-03-01T23:38:39.709339'
last_modified_at: '2022-03-01T23:38:39.709347'
